Cray-HPE/cray-site-init

- cmd/init.go
- cmd/validate.go
- pkg/csi/config.go
- pkg/csi/defaults.go
- pkg/csi/logical_ncn.go
- pkg/csi/networkBuilder.go
- pkg/pit/dnsmasq.go
- pkg/pit/networks.go
The CMN (Customer Management Network) will provide ingress administrative access to the system instead of the CAN as part of the CAN bifurcation process.  The CAN will remain in place, but be relegated to non-administrative (ie. regular user) traffic. This changes adds plumbing for the CMN. 
Default VLAN: 6
Default IPv4 Subnet: 10.103.6.0/24
New files:
```<hostname>/
dnsmasq.d/
CMN.conf
pit-files/
ifcfg-vlan006
```
New structure in sls_input_file.json:
```
"CMN": {
"Name": "CMN",
"FullName": "Customer Management Network",
"IPRanges": [
"10.103.6.0/24"
],
"Type": "ethernet",
"ExtraProperties": {
"CIDR": "10.103.6.0/24",
"VlanRange": [
6
],
"MTU": 9000,
"Subnets": [
{
"FullName": "CMN Static Pool MetalLB",
"CIDR": "10.103.6.112/28",
"Name": "cmn_metallb_static_pool",
"VlanID": 6,
"Gateway": …
```
> CASMNET-690 Add CMN for bifurcated CAN and make VLAN handling consistent

- .gitignore
- Makefile
- cmd/cabinet_input_file_test.go
- cmd/config.go
- cmd/dump.go
- cmd/gen-sls.go
- cmd/gen-sls_test.go
- cmd/get.go
- cmd/get_test.go
- cmd/init.go
- cmd/init_integration_test.go
- cmd/init_test.go
- cmd/load.go
- cmd/manage_input_files.go
- cmd/root.go
- pkg/csi/cabinets_test.go
- pkg/csi/logical_ncn_test.go
- pkg/csi/sls-state-generator_test.go
- pkg/csi/sls_test.go
- pkg/csi/switches_test.go
- pkg/csi/util.go
- Improves `init_test.go` by validating configs by running them through `config init`
- Adds a `get_test.go`, which gets the configs for the above
- Loads the `system_config.yaml` when the program first runs to better align with cobra/viper documentation.  This also allows the addition of a global `--config` flag, which allows users to pass in a different config (this mechanism is what is used to successfully implement a `config init` test in `init_test.go`).
- Relocates cobra `addCommands` into a single file so you can see all the commands that get added
- Removes unused code
- Sets appropriate argument limitations on a few subcommands
- Adds a function to `uitl.go`, which enables the testing of subcommands
- Improves the detection of seed files, by looking for them in the same location …
> MTL-1340 add an integration test for config init

- .gitignore
- Makefile
- cmd/cabinet_input_file_test.go
- cmd/config.go
- cmd/dump.go
- cmd/gen-sls.go
- cmd/gen-sls_test.go
- cmd/get.go
- cmd/get_test.go
- cmd/init.go
- cmd/init_integration_test.go
- cmd/init_test.go
- cmd/load.go
- cmd/manage_input_files.go
- cmd/root.go
- cmd/version.go
- internal/files/common.go
- pkg/csi/cabinets_test.go
- pkg/csi/logical_ncn_test.go
- pkg/csi/sls-state-generator_test.go
- pkg/csi/sls_test.go
- pkg/csi/switches_test.go
- pkg/csi/util.go
Restores `make integrate` functionality to generate configs using `csi config init`.  Previously, #13  appeared to work, but resulted in `csi version` not displaying anything and the `config init` command sometimes not working.  I believe this was due to the cobra config flags not being bound to viper.  I have fixed this by adding `v.BindPFlags(cmd.Flags())` to the `init.go` and `version.go` so it is aware of the config being used.  There is also more error-checking on the config file being passed in.
This does change the way the config file is loaded to a more standard way described in the cobra docs.  We were loading our config in more than one place, and this aims to standardize it a bit more, while allowing the integration tests to still work.
> Integrate test (MTL-1421 and MTL-1400)

- internal/files/metadata-schema.json
This adds a json schema for cloud-init metadata.  It is unused at the moment, but it can be implemented in manner similar to  https://github.com/Cray-HPE/cray-site-init/pull/37
Please also see https://github.com/Cray-HPE/community/issues/19 as this is the first step towards that endeavor.
> MTL-1465 add json schema for cloud-init metadata

- .github/PULL_REQUEST_TEMPLATE.md
- pkg/pit/basecamp.go
- Requires https://github.com/Cray-HPE/node-image-build/pull/71
- Relates to CASMTRIAGE-2522 CASMINST-2120
Removes unused `can-gw` from metadata.
N/A 
This removed value will no longer need populating by hand, some metadata on older vintages of installs may contain this KVP. The KVP is now no longer used, so it is just extra data now in those older vintages.
> CASMTRIAGE-2522 remove unused cangw metadata

- pkg/pit/basecamp.go
- Fixes [CASMPET-4885](https://connect.us.cray.com/jira/browse/CASMPET-4885)
This will attempt to join the storage nodes to spire the first time an
NCN is booted. It should fail until spire-server is running in the k8s
cluster. This is expected to succeed when ncn-m001 is rebooted. It will
not attempt to join nodes that already exist and contains a spire-server
healthcheck that times out after 5 minutes. This health check will fail
until sysmgmt is installed via loftsman.
Script has been run on internal systems manually. However, it has not been run this way before.
Ran the script multiple times. It checks to see if a storage node is already joined to spire and if so it doesn't attempt to do anything else with that node. If it's not joined then it will join the node.
If …
> CASMPET-4885 Run join-spire-on-storage script

- cmd/shcd.go
- cmd/shcd_integration_test.go
- cmd/shcd_test.go
- testdata/expected/application_node_config.yaml
- testdata/expected/hmn_connections.json
- testdata/expected/ncn_metadata.csv
- testdata/expected/switch_metadata.csv
- Partially implements MTL-1457
Generates an `ncn_metadata.csv` file _with_ xnames, but _without_ MAC addresses (MACs are coming in a subsequent PR)
N/A
Low.
> MTL-1457 generate partially accurate ncn_metadata from shcd.json

- cmd/automation-ncn-preflight.go
- pkg/csi/networkBuilder.go
- Fixes CASMINST-2541
- Bugfix Pull Request https://github.com/Cray-HPE/cray-site-init/pull/94
A change (bf84bdf23671fc12d880f87ed62effcb2008d778) several months ago filtered out spire and api_gw values from the istioingressgateway list in an effort to both deprecate underscores in names as well as prevent both the HMN and NMN gateways from showing up in DNS, creating a bad pseudo DNS Round-Robin lookup which (will always) fail on HMN.  The previous change looked for "api_gw" and the compare function required an exact name (like "api_gw_service") so the name was not filtered properly from the list.
This change fully removes the "underscore" gateway values, but brings in CSM 1.2 requirements the the HMNLB not have any istio ingress gateway records.
Previously removed records …
> Remove api gw and variations from HMNLB

- Jenkinsfile.github
Builds of signed RPMs have been broken since the 24th of November this year. This PR fixes that by adjusting the Jenkinsfile to accommodate whatever change lead to the permission/ownership problem blocking the ClamAV scan.
Errors observed from `main` and git-tags since the 24th:
```bash
+ bash -c '/usr/bin/scan_clamav.sh | tee /tmp/scan_dir/clamavscan-1.log'
tee: /tmp/scan_dir/clamavscan-1.log: Permission denied
```
> Fix Signed RPM Builds Dying on ClamAV Permission Denied Errors

- cmd/gen-sls.go
- cmd/init.go
- cmd/init_test.go
- pkg/csi/defaults.go
- pkg/csi/network.go
- pkg/pit/dnsmasq.go
- pkg/pit/metallb.go
- Fixes CASMINST-3670
- Fixes CASMNET-1165
Previously CSI hard coded the BICAN toggle to "CMN" thinking that other tools would toggle live.  This change **requires** the user to pick a BICAN network via the new `bican-user-network-name` flag.  Once enabled the "other possible user network" will not be created by default.  For instance, if the user selects the CAN for BICAN, then the CHN will not be created.  This flag has the same behavior and same naming as the one used in the CSM 1.0 to 1.2 SLS upgrade script.
To allow more flexibility for pure development and testing and maintain parity with behavior in the SLS upgrade script, this change also adds the `retain-unused-user-network` flag.  By default his flag is off.  If enabled, it will preserve "the other user network".  For example if …
> CASMNET-1165 and CASMINST-3670 Edge router cleanup and required CHN/CAN toggle

- pkg/pit/customizations_yaml.go
We need prevent UAIs from getting to CMN like we do with NMNLB.   The way this is being accomplished with NMNLB is that a route exists on the UAI that goes to a gateway that it cannot get to.   We are doing the same thing for CMN by adding the CMN subnet to macvlan routes defined in customizations.yaml.  This causes it to be added to the relevant network attachment definitions.
- Fixes #CASMINST-4283
I did a local build of CSI.  I ran "csi config init" with the resulting binary using the seed files from hela.   I verified that the correct CMN route (10.103.0.0./25) was added to the customizations.yaml generated by CSI.
```
macvlansetup:
nmn_subnet: 10.252.2.0/23
nmn_supernet: 10.252.0.0/17
nmn_supernet_gateway: 10.252.0.1
nmn_vlan: bond0.nmn0
nmn_reservation_start: 10.252.2.10 …
```
> CASMINST-4283: Add CMN route to net attach defs

- pkg/csi/sls-state-generator.go
- In order to have interoperability between the HMN-SHCD parser and CANU we need to be able to have 0 as a destination port number on the HMN tab of the SHCD.
- This change allows SLS to accept 0 as a port number.  This is the same behavior as leaving it blank.
- Fixes # CASMINST-4549
Tested locally.  All tests passed.
Generated SLS file has no differences with a "" or "0" as port destination.
Generated CSI data multiple times.
> CASMINST-4549 1.2

- pkg/csi/sls-state-generator.go
- In order to have interoperability between the HMN-SHCD parser and CANU we need to be able to have 0 as a destination port number on the HMN tab of the SHCD.
- This change allows SLS to accept 0 as a port number.  This is the same behavior as leaving it blank.
- Fixes # CASMINST-4549
Tested locally.  All tests passed.
Generated SLS file has no differences with a "" or "0" as port destination.
Generated CSI data multiple times.
> CASMINST-4549 allow destination port to be 0 in SLS

- Jenkinsfile.github
The previously used image was making use of a private key from an internal server. This image no longer contains internal security exploits, but contains the same toolset.
> Replace Image

- .github/workflows/shellcheck.yml
- pkg/pit/basecamp.go
- Fixes: [CASMTRIAGE-3640](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3640)
`csi` currently looks at the list of networks associated with an NCN to build the NTP allow list however this does not include the NMN_RVR, NMN_MTN, HMN_RVR, and HMN_MTN networks.
This change causes all the NMN/HMN networks to be included excluding the NMNLB and HMNLB networks.
Using seed data from `hela` the generated NTP allow list is as follows.
```
"allow": [
"10.103.9.10/25",
"10.252.1.9/17",
"10.103.0.24/25",
"10.254.1.14/17",
"10.1.1.7/16"
],
```
With code change
```
"allow": [
"10.252.0.0/17",
"10.100.0.0/17",
"10.254.0.0/17",
"10.104.0.0/17",
"10.107.0.0/17",
"10.106.0.0/17"
],
```
> CASMTRIAGE-3640 - Add all NMN and HMN networks to the NTP allow list

- Makefile
- cmd/version.go
- pkg/version/base.go
- pkg/version/version.go
- Fixes: MTL-1836
- Relates to: #179 
- Docs Pull Request
App Version reports '..' as its version since the removal of the `.version` file.
```bash
CRAY-Site-Init build signature...
Build Commit   : d034152d80558e7463fc3ccf1675b03b2c9ef86d-MTL-1836-dirty
Build Time     : 2022-07-05T16:06:38Z
Go Version     : go1.16.3
Version        : v1.20.1-1-gd034152d
Platform       : darwin/amd64
```
> MTL-1836 Remove App Version

- cmd/cabinet_input_file_test.go
- Fixes: MTL-1849
The `TestCabinetDefinitionWithHill` unit test wasn't fully updated after the https://github.com/Cray-HPE/cray-site-init/pull/203 was merged. Basically the test needs to be aware of the new EX{20,25,30,40}00 cabinet kinds.
As a sanity check I backported my test fix into the `release/1.2` code base, and observed that it passed: https://github.com/Cray-HPE/cray-site-init/compare/release/1.2...bugfix/MTL-1849-csm-1.2?expand=1 
I also took a note of the contents of the `cabinetDetailList` variable was to compare it with the contents of it on the `main` branch as a sanity check to verify my changes in https://github.com/Cray-HPE/cray-site-init/pull/203 adversely affected it.
From the release 1.2 branch for what the contents of `cabinetDetailList`` looks …
> MTL-1849: Fix TestCabinetDefinitionWithHill after EX2500 cabinet support added

- .gitignore
- .license_check.yaml
- cmd/shcd_test.go
- pkg/csi/sls-state-generator.go
- pkg/csi/sls-state-generator_test.go
- pkg/csi/sls.go
- pkg/csi/sls_test.go
- testdata/expected/application_node_config.yaml
- Fixes: MTL-1850
- Relates to: MTL-1848
The test was working but the LICENSE included in the expected test file was causing the test to flunk the comparison of actual to expected.
This updates `.license_check.yaml` to ignore `testdata/expected/*` files, and also removes created files from tests in `cmd/shcd_test.go`.
> MTL-1850 Fix TestCreateApplicationNodeConfig

- .github/dependabot.yml
- Fixes: MTL-1253
From documentation, `vendor` should not be set or this will fail.
Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#vendor
This should fix this error seen at https://github.com/Cray-HPE/cray-site-init/network/updates
```
The property '#/updates/0/' contains additional properties ["vendor"] outside of the schema when none are allowed
```
> MTL-1253 Dependabot remove `vendor`

- pkg/pit/customizations_yaml.go
- Fixes CASMUSER-3028
- Fixes CASMUSER-3050
CSI adds "routes" for the UAI net-attach-definition customizations to invalid IPs as a blackhole for traffic that should not go out the weave net over the default route.
Add two new routes for HMN and HMNLB.
I tested this with the net-attach-def set to ipvlan/hsn and macvlan/nmn. I pulled the new routes from a locally built `csi` using hermod seed files. The new routes are shown here:
```
routes:
- dst: 10.92.100.0/24        <-- new HMNLB
gw: 10.252.2.6
- dst: 10.254.0.0/17        <-- new HMN
gw: 10.252.2.6
- dst: 10.101.3.0/25
gw: 10.252.0.1
- dst: 10.94.100.0/24
gw: 10.252.2.6
- dst: 10.106.0.0/17
gw: 10.252.0.1
```
With a modified net-attach-def including these routes, I could not hit IPs on those networks as intended. …
> CASMUSER-3028: Add a blackhole route for the HMN and HMNLB

- pkg/bss/types.go
- pkg/pit/basecamp.go
- Relates to: MTL-1858 https://github.com/Cray-HPE/node-images/pull/420
The `join-spire-on-storage.sh` script was lingering in a random folder, it was moved by MTL-1858 into a subdir. This code changes the runcmd to invoke it in the new place.
> MTL-1858 Script moved to subdir

- cmd/shcd_test.go
- pkg/shcd/shcd.go
- testdata/expected/surtur_switch_metadata.csv
- testdata/expected/switch_metadata.csv
- testdata/fixtures/surtur_valid_ccj.json
- Fixes: [CASMINST-4903](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4903)
Better handle the case where the CANU generated ccj file may contain errors caused by bad SHCD formatting. For example the rack elevation "U" location being uppercase when the code expects lowercase.
Tested on surtur, command now functions as expected
```
surtur-ncn-m001-pit:/var/www/ephemeral/prep/cspiller # csi config shcd surtur-full-paddle.json -ANS
2022/07/20 09:17:26 Created "switch_metadata.csv" from SHCD data
2022/07/20 09:17:26 Created "application_node_config.yaml" from SHCD data
2022/07/20 09:17:26 Created "ncn_metadata.csv" from SHCD data
```
Previously it failed
```
surtur-ncn-m001-pit:/var/www/ephemeral/prep/cspiller # csi config shcd surtur-full-paddle.json -ANS …
```
> CASMINST-4903 - csi should better handle invalid input in the paddle file

- cmd/upgrade-metadata.go
- Fixes: MTL-1876
This change switches the `updateBSS12to13()` function to set the NCNs to use private buckets.
> MTL-1876 Private Buckets for Upgrades

- .github/CODEOWNERS
- cmd/handoff-bss-metadata.go
- Fixes: CASMINST-5290
- Relates to: MTL-1876 #232 
This ensures that either of the mutually exclusive groups are required when invoking `csi handoff bss-metadata`, while also removing the possibility of hitting a slicing error on bad regex matches.
> CASMINST-5290 Fix `bss-metadata`

- cmd/populate.go
- Relates to: MTL-1695
Deprecates `csi pit populate`.
Now `pit populate` isn't shown in the usage, but if it is invoked it'll print this message:
```
Command "populate" is deprecated, No longer used for CSM 1.3 or newer CSM installations.
```
Before:
```bash
surtur-ncn-m001-pit:~ # csi pit --help
Interact with the Pre-Install Toolkit (LiveCD);
create, validate, or re-create a new or old USB stick with
the liveCD tool. Fetches artifacts for deployment.
Usage:
csi pit [flags]
csi pit [command]
Available Commands:
format      Formats a disk as a LiveCD
get         Downloads artifacts
populate    Populates the LiveCD with configs
validate    Runs unit tests
Flags:
-h, --help   help for pit
Global Flags:
--config string   config file
Use "csi pit [command] --help" for more …
```
> MTL-1695 `pit populate` is no longer used

- cmd/populate.go
- Relates to: MTL-1695
Deprecates `csi pit populate`.
Now `pit populate` isn't shown in the usage, but if it is invoked it'll print this message:
```
Command "populate" is deprecated, No longer used for CSM 1.3 or newer CSM installations.
```
Before:
```bash
surtur-ncn-m001-pit:~ # csi pit --help
Interact with the Pre-Install Toolkit (LiveCD);
create, validate, or re-create a new or old USB stick with
the liveCD tool. Fetches artifacts for deployment.
Usage:
csi pit [flags]
csi pit [command]
Available Commands:
format      Formats a disk as a LiveCD
get         Downloads artifacts
populate    Populates the LiveCD with configs
validate    Runs unit tests
Flags:
-h, --help   help for pit
Global Flags:
--config string   config file
Use "csi pit [command] --help" for more …
```
> MTL-1695 deprecate populate

- cmd/init.go
- Fixes: MTL-1971
This value contols which `system_config.yaml` files are accepted, forcing the user to update the file when going to a new CSM release. Otherwise old values (deprecated, removed) and new values can be accidentally skipped or set incorrectly between releases.
This effectively denies any config file that isn't for 1.4.
> MTL-1971 Accept `1.4` `system_config.yaml` files

- cmd/shcd.go
- cmd/shcd_test.go
- pkg/shcd/shcd.go
- testdata/expected/hmn_connections.json
- testdata/expected/surtur_switch_metadata.csv
- testdata/expected/switch_metadata.csv
- Fixes: CASMINST-5040.  I used the ccj.json from that ticket (that failed to generate good data previously) and used it to validate the code in the PR is much closer to reality
- Relates to: CASMINST-5089
This PR fixes a few things:
- `csi` would ignore the flags passed to `config shcd` and just generate every seed file.  It no longer does that, so users can generate a specific seed file if they desire
- `csi` did not generate correct data for the seed files.  This was mainly due to the schema changes `canu` introduced, and this code was never updated to work with it.  Specifically, the dense node/subrack capabilities added to canu caused the existing code to provide inaccurate data when creating the seed files.  the data it generates is more accurate, but there are still a few …
> improve auto seed file generation accuracy

- cmd/handoff-bss-metadata.go
- Fixes: [CASMINST-5255](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5255)
The `csi handoff bss-metadata` command panics if the supplied SSH password is incorrect resulting in output that is confusing to the user.
This PR causes the SSH failure to exit a little more gracefully with output that is helpful to the user rather than panicking and dumping a stack trace.
Old output
```
root@starlord-ncn-m001-pit 2022-08-18 06:33:56 /var/www/ephemeral/prep/admin # csi handoff bss-metadata --data-file "${PITDATA}/configs/data.json" || echo "ERROR: csi handoff bss-metadata failed"
2022/08/18 06:33:58 Getting management NCNs from SLS...
2022/08/18 06:33:58 Done getting management NCNs from SLS.
2022/08/18 06:33:58 Building BSS metadata for NCNs...
Enter root password …
```
> CASMINST-5255 - "csi handoff bss-metadata" panics if supplied password is incorrect

- cmd/init.go
- pkg/pit/basecamp.go
- Fixes: [CASMPET-6145](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6145)
- Relates to: MTL-1971
This adds cilium-operator-replicas, k8s-primary-cni, and kube-proxy-replacement the basecamp output.
These are optional and will default if not specified.   There is validation for each of these if they are specified.
This also sets the expected CSM version to 1.4.
Tested this with various valid and invalid combinations of the three additional fields.
Ran csi config init multiple times in a row.
Low risk.   The default for k8s-primary-cni is still set to weave.   The other two will be ignored unless k8s-primary-cni is set to cilium.
> CASMPET-6145: Add cilium-operator-replicas, k8s-primary-cni, and kube-proxy-replacement

- .github/workflows/ci.yml
- Jenkinsfile.github
- go.mod
- Relates to: MTL-1708
Continue to build and publish SP3 RPMs while publishing SP4 RPMs.
Also upgrade to Go 1.19 since.
The SLES 15SP3 build creates an RPM with SP3 metadata and publishes it to `sle-15sp3`:
```bash
Name        : cray-site-init
Version     : 1.29.0~1~g50e3dc0b
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 65553484
License     : MIT License
Signature   : (none)
Source RPM  : cray-site-init-1.29.0~1~g50e3dc0b-1.src.rpm
Build Date  : Fri 02 Dec 2022 08:27:02 PM UTC
Build Host  : 7a5549c14ea6
Relocations : (not relocatable)
Vendor      : Cray Inc.
URL         : https://github.com/Cray-HPE/cray-site-init.git
Summary     : HPCaaS configuration and deployment tool for bare-metal or reinstallations …
```
> MTL-1708 Build & Publish SP4 RPMs

- cmd/init.go
- Fixes: MTL-2097
- Relates to: https://github.com/Cray-HPE/cray-site-init/pull/158
In 1.3 and newer, indicate that --site-dns should be used and not --ipv4-resolvers.  The latter doesn't actually end up in the generated configuration. At some point this will be removed entirely.
> CASMINST-1025: use site-dns instead of ipv4-resolvers

- cmd/init.go
- Fixes: CASMINST-1025
In 1.3 and newer, indicate that --site-dns should be used and not --ipv4-resolvers.  The latter doesn't actually end up in the generated configuration. At some point this will be removed entirely.
> CASMINST-1025: use site-dns instead of ipv4-resolvers (#289)

- .gitignore
- cmd/empty.go
- Fixes: MTL-2081
- Relates to: https://github.com/Cray-HPE/cray-site-init/pull/295
If a `system_config.yaml` file already exists, do not clobber it when invoking `csi config init empty`.
```bash
[808]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/cray-site-init> ./bin/csi config init empty
2023/03/08 13:35:18 Using config file: /Users/rusty/gitstuffs/cray-shasta/cray-site-init/system_config.yaml
2023/03/08 13:35:18 Config File "system_config.yaml" Already Exists
```
> MTL-2081 Prevent `empty` from clobbering

- cmd/handoff-bss-metadata.go
- Fixes: [CASMINST-6333](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6333)
- Fixes: [CASMINST-6329](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6329)
This change adds passwordless (public-key) authentication to the set of authenticators used by the ssh sessions for csi handoff-metadata and adds a password based authenticator that prompts once for the NCN password and then remembers it for subsequent SSH sessions. This replaces the logic that prompts up front for the NCN password all the time. The passwordless authenticator runs first, and, if it succeeds, no password prompt is given. If that fails, a password prompt is given and the supplied password is cached and used for subsequent NCN logins. If the cached password doesn't work for one of the …
> MTL-2148 / MTL-1431 make bond0 optional and allow passwordless ssh

- cmd/patch/patch-packages.go
- cmd/root.go
- pkg/pit/dnsmasq.go
- Relates to: #324 
The `repos` key is actually nested under `zypper`, cloud-init specifically looks for the parent key `zypper` for determining to run the `zypper_add_repos` module.
What the JSON looked like before when patched:
```json
"packages": [
"cani",
"canu",
"cray-cmstools-crayctldeploy",
"csm-testing",
"goss-servers",
"iuf-cli",
"libcsm",
"platform-utils"
],
"runcmd": [
"/srv/cray/scripts/metal/net-init.sh",
"/srv/cray/scripts/common/update_ca_certs.py",
"/srv/cray/scripts/metal/install.sh",
"/srv/cray/scripts/common/pre-load-images.sh",
"/srv/cray/scripts/common/storage-ceph-cloudinit.sh",
"touch /etc/cloud/cloud-init.disabled"
],
"timezone": "UTC",
"write_files": [
{
"content": "10.106.0.0/22 10.252.0.1 - bond0.nmn0\n10.1.0.0/16 10.252.0.1 - …
```
> MTL-2000 Needs top-level `Zypper` key

- cmd/patch/patch-packages.go
- Relates to: #333 
Handle `cloud-init.yaml` with or without a root `zypper` key.
Tested with both formats, and both produced valid `data.json` with the `zypper` root key present.
> MTL-2000 Handle both formats

- pkg/pit/dnsmasq.go
- Relates to: MTL-2000
Adds `packages.local` as a CNAME to `packages.nmn`. This will trump `statics.conf`, causing `packages.local` to resolve to the PIT nexus while DNSMasq is running.
`statics.conf` must remain the same for CSM handoff to function properly, for unbound and istio to properly setup `packages.local`.
This is compatible with the MTL-2000 cloud-init code, this new CNAME will allow `packages.local` to correctly resolve to PIT nexus during bootstrap. Then, during the csm install, when DNSMasq is shutdown `packages.local` will begin resolving to k8s nexus.
> MTL-2000 `packages.local` cname

- cmd/patch/patch-packages.go
- pkg/pit/dnsmasq.go
- Fixes: CASMTRIAGE-6178
- Relates to: MTL-2000
This resolves two issues.
The URLs used are not resolving properly during bootstrap due to `packages.local` existing only on the NMN. When the node starts up, it initially only has DNS for the MTL network. The MTL network is unaware of any `.nmn` search domains, and fails to resolve `packages.local`. The following error is observed:
```bash
Retrieving repository 'csm-noos' metadata [.error]
Repository 'csm-noos' is invalid.
[csm-noos|https://packages.local/repository/csm-noos?ssl_verify=no] Valid metadata not found at specified URL
History:
- [|] Error trying to read from 'https://packages.local/repository/csm-noos?ssl_verify=no'
- Timeout exceeded when accessing …
```
> CASMTRIAGE-6178 Cloud-init Zypper Repos and Packages Fix

- cmd/init.go
- pkg/pit/basecamp.go
- Fixes:  https://jira-pro.it.hpe.com:8443/browse/CASMPET-6835
Changes kube-proxy-replacement to cilium-kube-proxy-replacement to match up with kubernetes-cloudinit.sh.
> CASMPET-6835: Fix cilium-kube-proxy-replacement name

- pkg/pit/dnsmasq.go
- Fixes: [CASMINST-6834](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6834)
If a system is configured for CHN then the dnsmasq.d/statics.conf file generated by `csi config init` contains CAN entries with a blank IP address.
```
dhcp-host=id:x3100c0s19b0n0,set:ncn-s001,5c:ed:8c:86:43:36,5c:ed:8c:21:6f:90,10.1.1.4,ncn-s001,20m # MTL
dhcp-host=id:x3100c0s19b0n0,set:ncn-s001,5c:ed:8c:86:43:36,5c:ed:8c:21:6f:90,10.252.1.6,ncn-s001,20m # Bond0 Mac0/Mac1
dhcp-host=id:x3100c0s19b0n0,set:ncn-s001,5c:ed:8c:86:43:36,5c:ed:8c:21:6f:90,10.254.1.8,ncn-s001,20m # HMN
dhcp-host=id:x3100c0s19b0n0,set:ncn-s001,5c:ed:8c:86:43:36,5c:ed:8c:21:6f:90,,ncn-s001,20m # CAN
dhcp-host=5c:ed:8c:3c:b6:76,10.254.1.7,ncn-s001-mgmt,20m #HMN
host-record=ncn-s001,ncn-s001.can, …
```
> CASMINST-6834 - CSI generates blank CAN dnsmasq configuration if system configured for CHN

- cmd/handoff-bss-metadata.go
- pkg/pit/basecamp.go
- Fixes: [CASMPET-6917](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6917)
`csi` already ignores Weave `veth` interfaces when populating HSM ethernetInterfaces with NCN MAC addresses.
A similar exclusion is required for Cilium `lxc` interfaces to avoid cluttering up ethernetInterfaces with unnecessary records.
This PR also disables the kube-proxy replacement by default as there are problems with it and TFTP ([CASMPET-6763](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6763))
This was tested on surtur and had the desired effect however the system was reinstalled before I could preserve the output and I cannot test this change again until the next CSM 1.6 fresh install with Cilium as the default CNI.
> CASMPET-6917 - csi handoff bss-metadata should ignore Cilium lxc interfaces

- Makefile
Minor detail, but if `GOARCH` is only set if the resolved `ARCH` is explicitly `aarch64` or `x86_64`. On M1/M2/M3 MacBooks the `ARCH` resolves to `arm64`.
This is not very important, because `GOARCH` will auto-resolve itself when Go compiles, but it looks goofy in the build output with `GOARCH=<nothing>`.
Before:
```bash
rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/csi> make bin/csi
GOOS=darwin GOARCH= go build -o bin/csi -ldflags "\
-X github.com/Cray-HPE/cray-site-init/pkg/version.version=v1.32.7 \
-X github.com/Cray-HPE/cray-site-init/pkg/version.buildDate=2024-05-08T03:08:31Z \
-X github.com/Cray-HPE/cray-site-init/pkg/version.sha1ver=ebab5feccbafb9cad370e3be82f78ac19e3950be-main-dirty"
ld: warning: -bind_at_load is deprecated on macOS
```
After:
```bash …
```
> Always set `GOARCH`

- cmd/init.go
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7012
Validate only non-empty ipv4 addresses.
Ignore **chn-gateway: ""**
Validate **chn-gateway: 10.102.103.129**
none known
> CASMTRIAGE-7012

- .github/workflows/pages.yml
- (fiengly) fixes: broken docs generation and publication by reverting and pinning the action to a previous hugo version.  It seems to have broke beginning with [`v1.230.0`](https://github.com/gohugoio/hugo/releases/tag/v0.123.0)
> Fix broken hugo docs generation

- pkg/cli/automation/ncn/ncn.go
- Fixes: MTL-2404
- Relates to: #391 
The `automate ncn` command's `--kubeconfig` flag is not recognized by any subcommands.
Change the flag to a persistent flag in the `ncn` package.
**Before** `--kubeconfig` does *not* appear as a valid flag for the `kubernetes` subcommand.
```bash
[612]rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/csi> ./csi version
CRAY-Site-Init build signature...
Build Commit   : fe6eeacfbf447becf3af6cff386006628989c82b-main
Build Time     : 2024-06-30T07:00:31Z
Go Version     : go1.22.4
Version        : 1.33.1
Platform       : darwin/arm64
[613]rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/csi> ./csi automate ncn kubernetes --help
A series of subcommands that automates administrative tasks to Kubernetes.
Usage:
csi automate ncn kubernetes …
```
> MTL-2404 `--kubeconfig` flag is not recognized

- pkg/cli/pit/format.go
- pkg/cli/pit/format_test.go
- pkg/cli/pit/pit.go
this commit could have been a one line change to remove the
MarkFlagRequired() directive, but in an effort to improve the quality
and confidence of our tooling, I opted to create a new test for this.
this involved creating a new type, WriteLiveCDFunc, which is accepted as
a parameter.
this is required to replace the real implementation with a mock in the
go tests.  this is especially important in this function since it could
destructively format a disk, so if you accidently gave it some bad
parameters, there is a possibility it may format something unintended.
this also allows finer control over what portions of the function to
test.
in this case, I mererly test that the function does not require the
--write-script flag.
further tests could certainly be added, but as CSM is EOL, I am …
> make `csi pit format --write-script` optional to fix CASMTRIAGE-7156

- pkg/cli/handoff/data.go
Remove hsn kernel parameters
https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7380
Related PR:
- https://github.com/Cray-HPE/docs-csm/pull/5454
> CASMTRIAGE-7380

- pkg/cli/config/initialize/initialize.go
- pkg/cli/config/initialize/sls/networkBuilder.go
- pkg/networking/ipam.go
- pkg/networking/ipam_test.go
Previously CSI allowed VLANs to be used for multiple networks.  For example, VLAN 4 is the usual default for the HMN, but might also erroneously be used on the command line or `system_config.yaml` to specify other networks - say the NMN or CMN. This caused errors during installation and runtime for the switch configurations.
This change introduces VLAN validation and management in the IPAM module. The functions both allocate and free VLANs from management as well as check to see if a VLAN has previously been used or is in an incorrect range.  These functions have been used in `csi config init` after network structure initialization and assignment of VLAN values from the CLI and `system_config.yaml` values. While this is relatively late in the process, the random nature of the range loop …
> Add VLAN management with overlap and re-use checks

- pkg/cli/config/initialize/basecamp.go
- pkg/cli/config/initialize/initialize.go
- pkg/cli/config/initialize/networks.go
- pkg/cli/config/initialize/sls/networkBuilder.go
- pkg/networking/network.go
- Fixes: [MTL-2437](https://jira-pro.it.hpe.com:8443/browse/MTL-2437)
MTL-2437 prevented VLAN re-use and duplication.  Previous to that change both BICAN and MTL used VLAN 0.  This, for several reasons, is wrong.  MTL-2437 changed the default MTL VLAN to 1 from 0, which had no downstream impact on CANU or switch configs.  However, VLAN 0 was hard coded in `ifcfg` file generation and `dnsmasq` file generation so the change in MTL VLANs broke the PIT interfaces (both `bond0` and `bond0.mtl0` were IP'd with the same IP address.  Additionally, a dnsmasq file was generated for `bond0.mtl0` which is erroneous.
This change fixes the problem in two ways. First the MTL VLAN variable is used in `ifcfg` file generation.  Second, because of circular dependencies the `dnsmasq` …
> MTL-2508 Avoid hard coded vlans for MTL

- pkg/cli/config/initialize/sls/networkBuilder.go
- Fixes: [MTL-2484](https://jira-pro.it.hpe.com:8443/browse/MTL-2484)
The `kubeapi-vip` only exists on the NMN however records for it get generated in other SLS networks resulting in DNS entries for services that don't exist.
This PR removes `kubeapi-vip` from all networks other than the NMN 
Tested using local data
Old behaviour
```bash
$ jq -c '.Networks | to_entries[] | {"Network":.key, "VIP": .value.ExtraProperties.Subnets[] | select(.FullName|contains("Bootstrap")) | .IPReservations[] | select(.Name=="kubeapi-vip")}' sls_input_file.json
{"Network":"CHN","VIP":{"Name":"kubeapi-vip","IPAddress":"10.102.193.196","Comment":"k8s-virtual-ip"}}
{"Network":"CMN","VIP":{"Name":"kubeapi-vip","IPAddress":"10.102.193.18","Comment":"k8s-virtual-ip"}} …
```
> MTL-2484 - Remove kube-api from all but NMN

- .github/workflows/lint.yml
- .github/workflows/test.yml
The regexes for our workflows were inconsistent with one another.
They should be the same, and not limit themselves to `1.x.y` and `2.x.y`.
> Support any major version and optional `v`

- pkg/cli/config/initialize/basecamp.go
- Fixes: [CASMNET-2212](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2212)
CSM 1.7 will use the Cilium container network interface. This PR makes Cilium the default CNI for a fresh install.
Tested using data from wasp. Cilium is now the default CNI in the basecamp data.json file.
```
$ csi config init
...
2025/02/25 17:10:09 Detected CSM v1.7, setting k8s-primary-cni to Cilium
...
$ jq '.Global."meta-data"."k8s-primary-cni"' wasp/basecamp/data.json
"cilium"
```
If CSM version is < 1.7 then default to `weave` 
```
$ csi config init --csm-version 1.6
...
$ jq '.Global."meta-data"."k8s-primary-cni"' wasp/basecamp/data.json
"weave"
```
```
$ csi config init --csm-version 1.5
...
$ jq '.Global."meta-data"."k8s-primary-cni"' wasp/basecamp/data.json
"weave"
```
```
$ csi …
```
> CASMNET-2212 - Switch to install Cilium by default (not weave) in cloud-init

- pkg/kubernetes/utils.go
When run against Kubernetes 1.32 the `csi automate ncn kubernetes` command fails to delete the node.
```
ncn-m001:~ # csi automate ncn kubernetes --action delete-ncn --ncn ncn-m002 --kubeconfig /etc/kubernetes/admin.conf
2025/03/05 14:43:10 [Kubernetes DEBUG] ncn-m002 cordoned.
2025/03/05 14:43:10 [Kubernetes DEBUG] ncn-m002 cordoned.
2025/03/05 14:43:10 [Kubernetes WARNING] Retrying after error: %!w(*fmt.wrapError=&{failed to drain NCN: the server could not find the requested resource 0xc000906a00})
2025/03/05 14:43:12 [Kubernetes DEBUG] ncn-m002 cordoned.
2025/03/05 14:43:12 [Kubernetes WARNING] Retrying after error: %!w(*fmt.wrapError=&{failed to drain NCN: the server could not find the requested resource 0xc00098e320})
2025/03/05 14:43:14 Failed to delete ncn-m002: failed to delete …
```
> CASMTRIAGE-7917 - "csi automate ncn kubernetes" is failing to delete node

- pkg/cli/config/initialize/initialize.go
- pkg/cli/config/initialize/metallb.go
The version of MetalLB used in all current versions of CSM is old and configured by means of a Kubernetes ConfigMap.
Newer versions of MetalLB are configured by means of Custom Resource Definitions (IPAddressPool, BGPPeer, BGPAdvertisement).
```
ncn-m001:~ # kubectl -n metallb-system get bgpadvertisements.metallb.io
NAME                  IPADDRESSPOOLS                                         IPADDRESSPOOL SELECTORS   PEERS
customer-high-speed   ["customer-high-speed"]                                                          ["sw-edge-001"]
customer-management   ["customer-management-static","customer-management"]                             ["sw-spine-001-cmn","sw-spine-002-cmn"]
node-management       ["node-management","hardware-management"] …
```
> CASMNET-2318 - Add switch and network information to MetalLB data

- .github/workflows/lint.yml
- .github/workflows/shellcheck.yml
Fixes issues with the linter.
golangci-lint, when `only-new-issues` is set, only works for the main branches (post-merge) and on pull-request.
For pushes to feature branches, errors like the one below can be observed:
(excerpt from https://github.com/Cray-HPE/cray-site-init/actions/runs/16383180901/job/46298433164#step:4:23)
```
failed to fetch push patch: RequestError [HttpError]: Not Found - https://docs.github.com/rest/commits/commits#compare-two-commits
Prepared env in 862ms
at /home/runner/work/_actions/golangci/golangci-lint-action/v8/dist/run/index.js:44487:21
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/golangci/golangci-lint-action/v8/dist/run/index.js:44213:20)
at async …
```
> Lint changes

- pkg/cli/config/initialize/metallb.go
- Fixes: CASMINST-7398
- Relates to: #488 
PR #488 left some debug statements in the `metallb.yaml` file generation.
> CASMINST-7398 Remove debug statements

- pkg/cli/config/initialize/write.go
- Fixes: CASMINST-7395
- Relates to: #488 
- Docs Pull Request
The new flags, `csm-api-url`, `k8s-namespace`, and `k8s-secret-name` were not intended to be included in generated `system_config.yaml` files. This could be reconsidered, but they are primarily for development. If these are set, it could throw off a CSM install if they went unnoticed.
> CASMINST-7395 Omit recently added flags

- pkg/cli/config/initialize/initialize.go
- pkg/cli/config/initialize/pit_basecamp.go
- Fixes: CASMINST-7396
- Relates to: #488 
VShasta runs were reporting errors when munging `Global` data, the Global entry created after #488 changed the `user-data` value from a `map` to `nil`. This change causes Vshasta runs to barf during their PIT initialization.
Example: https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcsm-vshasta-deploy/detail/main/2129/
This change also includes a minor refactor to make the variables more clear as to what they contain with regards to meta-data vs user-data.
> CASMINST-7396 null global userdata
