Cray-HPE/cray-site-init

- README.md
> fix #3, revamp readme

- Jenkinsfile.github
- Makefile
This will mark anything merged to main, or with a tag, as s stable build. This means we'll start populating the new stable area in Artifactory for the LiveCD to pickup from, _and_ we'll get signed RPMs.
> Main is stable

- cmd/init.go
Default mountain-cabinets to 0 like we do for hill-cabinets
> Default mountain-cabinets to 0 like hill-cabinets

- cmd/handoff-bss-update_cloud-init.go
> MTL-1427 adjust usage line for user-data flag

- .github/workflows/pages.yml
> MTL-1400 auto gen csi command docs on merge

- Jenkinsfile.github
- Relates to MTL-1571
This enables changing the buildenv by simply updating the version
set in go.mod. By updating go.mod, Jenkins will auto-resolve the right
container base to use.
> MTL-1571 Make Updating Go Easier

- Jenkinsfile.github
Reverts Cray-HPE/cray-site-init#95
> Revert "Fix Signed RPM Builds Dying on ClamAV Permission Denied Errors"

- Jenkinsfile.github
Building as root is causing problems.
> Don't build as root

- .github/workflows/shellcheck.yml
- scripts/write-livecd.sh
- Partially implements MTL-1497
Adds shellcheck workflow to this repo.
N/A
Low
> add shellcheck workflow

- cmd/init.go
- pkg/csi/sls-state-generator.go
- Fixes # CASMINST-4671
Validates that the BGP ASN is within the private range.
Tested with Frigg system_config data.
Ran `csi config init` and got the same result multiple times.
No
> CASMINST-4671 main

- cmd/init.go
- Fixes # CASMINST-4671
Validates that the BGP ASN is within the private range.
Tested with Frigg system_config data.
Ran `csi config init` and got the same result multiple times.
No
> CASMINST-4671 add BGP ASN validation

- cmd/shcd.go
- cmd/shcd_test.go
- Relates to [MTL-1768](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1768)
Feature is not in production yet.
> Improve code readability and remove unused code

- cmd/shcd.go
- cmd/shcd_test.go
- go.mod
- go.sum
- vendor/github.com/Cray-HPE/hms-xname/LICENSE
- vendor/github.com/Cray-HPE/hms-xname/xnames/types.go
- vendor/github.com/Cray-HPE/hms-xname/xnames/util.go
- vendor/github.com/Cray-HPE/hms-xname/xnames/xnames.go
- vendor/github.com/Cray-HPE/hms-xname/xnametypes/hmstypes.go
- vendor/modules.txt
- Fixes [MTL-1769](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1769)
Feature not in production yet.
> MTL-1769 - Refactor create switchmetadata

- .license_check.yaml
- cmd/shcd_test.go
Fixes license checker by adding a custom license_check.yaml file to deal with corner cases.
> Add custom license_check.yaml fo exclude corner cases

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
New PR template from metal-templates.
> Updating template

- .github/PULL_REQUEST_TEMPLATE.md
Tidy-up whitespace from #193 .
> tidy-up whitespace

- .github/dependabot.yml
This adds a dependabot workflow that will make PRs (weekly) that auto-updates our dependencies.
This seemed like a good idea to help automate an area of the application that we usually don't give attention to.
> MTL-1253 Workflow for auto-updating dependencies

- Makefile
- Fixes: False positive tests.
The `make test` command pipes several items into `tee`, which fools the tester.
> Fix test failure

- Makefile
- Fixes: False positive tests.
The `make test` command pipes several items into `tee`, which fools the tester.
> Fix test failure 1.2

- pkg/pit/customizations_yaml.go
- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5428
Cephexporter only reports data on the first three storage nodes (running mon/mgr).
```
C02YT3JRLVCJ:cray-site-init bklein$ cat foo/foo/customizations.yaml  | grep -A3 nmn_ncn_storage_mons
nmn_ncn_storage_mons:
- 10.252.1.4
- 10.252.1.5
- 10.252.1.6
```
Good
Low
> Add separate list of storage nodes for cephExporter endpoints (CASMPET-5428)

- pkg/bss/types.go
Run `cloud-init.disabled` last.
> MTL-1961 Fix ordering

- pkg/pit/basecamp.go
- Fixes: MTL-1793
Better validates input of NTP data.  Specifically, it checks that each `peer`, `pool`, or `server` is a valid hostname or FQDN.  
The `--help` for `csi config init` shows the default slice with brackets, so that can lead users to assume the input needs them, when it is simply looking for a string of domains, separated with commas, when in fact it leads to invalid domains, such as `[ncn-m001`.  
Really, there should be more checks along the way, but stopping bad input goes a long way.
invalid trailing `]`
```
$ csi config init --ntp-servers ncn-m001,ncn-m002,ncn-m003,ncn-w001,ncn-w002,ncn-w003,ncn-s001,ncn-s002,ncn-s003]
2022/10/21 13:25:15 invalid ntp server: ncn-s003]
```
invalid `[` before …
> MTL-1793 better validate ntp pools, peers, and servers

- Jenkinsfile.github
Minor `Jenkinsfile` and license updates. This simplifies some things in the `Jenkinsfile`, and conforms to my current template I'm using for several RPMs used in the PIT and NCN images.
> Updating template for `Jenkinsfile`

- scripts/write-livecd.sh
- Fixes: MTL-1476 MTL-2035
- Requires: https://github.com/Cray-HPE/node-images/pull/608
This includes support for the new LiveCD ISO being built from node-images (instead of the  cray-pre-install-toolkit). The new ISO has a fixed GPT structure, no longer showing up as MSDOS. This entails some modifications to the `parted` commands.
This also has additional steps for installing the dependent directory structure required for overlayFS to work properly. The new ISO uses `dmsquash-live` instead of the kiwi dracut module for handling the overlayFS, this entails needing certain directories to exist during the boot. This is an important change for MTL-2035.
> MTL-1476 Support GPT ISO and overlayFS

- .github/actions/prepare-artifacts/action.yml
- .github/workflows/promote-prerelease.yml
- .github/workflows/promote-release.yml
- Fixes: #288 
Automatically publishes releases and attaches artifacts.
This waits for the RPMs to appear in Artifactory and then publishes them to a GitHub release.
> Fixes #288

- .github/actions/prepare-artifacts/action.yml
Key off of the `vcs.branch`, since that will have the `^v` if it is used.
> Relates to #288

- cmd/handoff-bss-metadata.go
- Fixes: CASMTRIAGE-5072
- Relates to: #290 
Remove CSM Version specific items from the `handoff` command flow to mitigate risk. The handoff flow will work as it has been in current CSM 1.4 integration tests.
> Revert part of #290

- Jenkinsfile.github
Do not promote alphas, betas, or release candidates to stable.
[This build](https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcray-site-init/detail/v1.32.0rc1/1/pipeline) promoted a release candidate to stable. It has been moved to unstable by hand. This change fixes that so it doesn't happen again.
Also publishes to `noos`.
> Alpha, beta, and RC are not stable; publish to noos

- Jenkinsfile.github
- Relates to: #325 
There are a few too many doc steps that refer to a SLE based repository for installing cray-site-init at this time.
To facilitate the transition period, continue publishing to SP3 and SP4 directories. This can still do without the matrix builds, and we can just push the same RPM to all 3 places during this interim period.
> Also publish to sp3 and sp4

- cmd/patch/patch-packages.go
- Relates to: #324 
This statement is printing the loaded YAML file, it was used for debug and should be removed.
Example of debug print:
```json
{[{csm-noos csm-noos https://packages/repository/csm-noos?ssl_verify=no 1 1 0} {csm-sle csm-sle-${releasever_major}sp${releasever_minor} https://packages/repository/csm-sle-${releasever_major}sp${releasever_minor}?ssl_verify=no 1 1 0}] [canu cray-cmstools-crayctldeploy csm-testing goss-servers iuf-cli libcsm platform-utils]}
```
> Remove debug statement

- cmd/init.go
Require one of **can-gateway** OR **chn-gateway** but do not allow both.
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMINST-5905
> CASMINST-5905

- Jenkinsfile.github
- cray-site-init.spec
- Fixes: MTL-2403
Installs shell completion scripts for bash and zsh.
Tab-completion example:
```bash
redbull-management:~ # csi
automate         (Tools used to automate system lifecycle events)                                         makedocs         (Create a set of markdown files for the docs in the [directory] (docs/ is the default))
completion       (Generate the autocompletion script for the specified shell)                             patch            (Apply patch operations)
config           (Interact with a Shasta config)                                                          pit              (Manipulate or Create a LiveCD (Pre-Install Toolkit))
handoff          (Runs migration steps to transition from LiveCD) …
```
> MTL-2403 shell completion for bash and zsh - build for aarch64

- .github/workflows/lint.yml
- .github/workflows/pages.yml
- .github/workflows/test.yml
- Makefile
- go.mod
- go.sum
- Fixes: MTL-2425
Update to Go 1.22
> MTL-2425 Go 1.22

- pkg/cli/config/initialize/initialize.go
- Fixes: MTL-2444
- Relates to: #391 
- Docs Pull Request
`s/CAN/CHN/`
> MTL-2444 Print out correct network name

- pkg/cli/config/initialize/basecamp.go
- Fixes: https://jira-pro.it.hpe.com:8443/browse/MTL-1832
> MTL-1832 followup -- fix for csm <1.6
